#!/usr/bin/python3
from sys import argv

with open(argv[1]) as f:
    for line in f:
        num = int(line)
        print("{:d}=".format(num), end='')
        if num % 2 == 0:
            print("{}*2".format(num//2))
            continue
        for b in range(3, num, 2):
            if num % b == 0:
                factor = num // b
                for j in range(3, factor, 2):
                    if factor % j == 0 or j == 0:
                        break
                print("{}*{}".format(factor, b))
                break
